// Docs: https://dbml.dbdiagram.io/docs

Enum activity_type {
  contribution
}

Enum contribution_status {
  claimed
}

Enum transaction_type {
  earn
}

Enum user_role {
  admin
  member
}

Table activities {
  id uuid [pk, default: `gen_random_uuid()`]
  created_at timestamp [not null, default: `now()`]
  title text [not null]
  date timestamp
  location text
  content text
  type activity_type [not null, default: 'contribution']
  project_id uuid [not null, ref: > project.id]
}

Table badges {
  id uuid [pk, default: `gen_random_uuid()`]
  created_at timestamp [not null, default: `now()`]
  name text [not null]
  value text [not null]
}

Table contribution_types {
  id uuid [pk, default: `gen_random_uuid()`]
  created_at timestamp [not null, default: `now()`]
  name text [not null]
  value text [not null]
  point bigint [not null, default: 50]
}

Table notifications {
  id bigint [pk, increment]
  created_at timestamp [not null, default: `now()`]
  user_id uuid [not null, ref: > users.id]
  is_read boolean [not null, default: false]
  message text
  type text [not null]
  url text
  project_id uuid [not null, ref: > project.id]
}

Table project {
  id uuid [pk, default: `gen_random_uuid()`]
  created_at timestamp [not null, default: `now()`]
  name text [not null]
  description text
}

Table project_prize_items {
  id bigint [pk, increment]
  created_at timestamp [not null, default: `now()`]
  point bigint [not null, default: 50]
  thumbnail_url text
  project_id uuid [not null, ref: > project.id]
  description text
  name text [not null]
}

Table user_badges {
  created_at timestamp [not null, default: `now()`]
  user_id uuid [pk, ref: > users.id]
  badge_id uuid [pk, ref: > badges.id]
}

Table user_contributions {
  id uuid [pk, default: `gen_random_uuid()`]
  created_at timestamp [not null, default: `now()`]
  date timestamp
  type_id uuid [not null, ref: > contribution_types.id]
  status contribution_status [not null, default: 'claimed']
  user_id uuid [not null, ref: > users.id]
  activity_id uuid [ref: > activities.id]
  project_id uuid [not null, ref: > project.id]
}

Table user_photos {
  id uuid [pk, default: `gen_random_uuid()`]
  created_at timestamp [not null, default: `now()`]
  url text [not null]
  user_id uuid [not null, ref: > users.id]
  user_contibution_id uuid [not null, ref: > user_contributions.id]
  project_id uuid [not null, ref: > project.id]
}

Table user_point_transactions {
  id uuid [pk, default: `gen_random_uuid()`]
  created_at timestamp [not null, default: `now()`]
  project_id uuid [not null, ref: > project.id]
  user_id uuid [not null, ref: > users.id]
  project_prize_id bigint [ref: > project_prize_items.id]
  point bigint [not null, default: 0]
  type transaction_type [not null, default: 'earn']
}

Table user_projects {
  user_id uuid [pk, ref: > users.id]
  created_at timestamp [not null, default: `now()`]
  project_id uuid [pk, ref: > project.id]
}

Table users {
  id uuid [pk]
  name text
  created_at timestamp [not null, default: `now()`]
  thumbnail_url text
  bio text
  total_points bigint [not null, default: 0]
  available_points bigint [not null, default: 0]
  role user_role [not null, default: 'admin']
}
