// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table projects {
  id uuid [pk, default: `gen_random_uuid()`]
  created_at timestamp [not null, default: `now()`]
  name text [not null]
  description text
  Note: '団体や活動などの母体を表すテーブル'
}

Table activity_tasks {
  id uuid [pk, default: `gen_random_uuid()`]
  name varchar
  data date
  location varchar
  capacity integer [not null, default: 0]
  parent_task_id uuid [not null, ref: > activities.id]
  project_id uuid [not null, ref: > projects.id]
  created_at timestamp [not null, default: `now()`]
  Note: '活動に紐づく最小のタスクを表すテーブル'
}

Table categories {
  id uuid [pk, default: `gen_random_uuid()`]
  name varchar [not null, unique]
  created_at timestamp [not null, default: `now()`]
  Note: '活動分野を表すテーブル'
}

Table activity_categories {
  id uuid [pk, default: `gen_random_uuid()`]
  activity_id uuid [not null, ref: > activities.id]
  category_id uuid [not null, ref: > categories.id]
  level integer
  created_at timestamp [not null, default: `now()`]
  Note: '活動分野と活動の関連テーブル'
}

Table activities {
  id uuid [pk, default: `gen_random_uuid()`]
  name varchar [not null, unique]
  project_id uuid [not null, ref: > projects.id]
  created_at timestamp [not null, default: `now()`]
  Note: '活動のテーブル'
}

Table user_activity_tasks {
  id uuid [pk, default: `gen_random_uuid()`]
  user_id uuid [not null, ref: > users.id]
  task_id uuid [not null, ref: > activity_tasks.id]
  created_at timestamp [not null, default: `now()`]
  Note: 'タスクとユーザーの関連テーブル'
}

enum roles {
  admin
  user
}

Table users {
  id uuid [pk, default: `gen_random_uuid()`]
  name varchar
  role roles [not null, default: 'user']
  total_points integer [not null, default: 0]
  available_points integer [not null, default: 0]
  created_at timestamp [not null, default: `now()`]
  Note: 'ユーザーテーブル'
}

Table user_badges {
  id uuid [pk, default: `gen_random_uuid()`]
  level integer [not null, default: 1]
  user_id uuid [not null, ref: > users.id]
  badge_id uuid [not null, ref: > badges.id]
  created_at timestamp [not null, default: `now()`]
  Note: 'ユーザーとバッジの関連を表すテーブル'
}

Table badges {
  id uuid [pk, default: `gen_random_uuid()`]
  name varchar [not null, unique]
  created_at timestamp [not null, default: `now()`]
  Note: 'バッジを表すテーブル'
}

enum transaction_type {
  earn
  spend
}

Table user_point_transactions {
  id uuid [pk, default: `gen_random_uuid()`]
  amount integer [not null]
  type transaction_type [not null, default: 'earn']
  user_id uuid [not null, ref: > users.id]
  project_id uuid [not null, ref: > projects.id]
  task_id uuid [ref: > activity_tasks.id]
  project_prize_item_id uuid [ref: > project_prize_items.id]
  created_at timestamp [not null, default: `now()`]
  Note: 'ユーザーとポイントの関連テーブル（ポイント履歴）'
}

Table project_prize_items {
  id uuid [pk, default: `gen_random_uuid()`]
  project_id uuid [not null, ref: > projects.id]
  name varchar [not null]
  description text
  created_at timestamp [not null, default: `now()`]
  Note: '特典を表すテーブル'
}